---
title: "COVID-19 Lof Disparate Impact"
author: "John Erickson"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Studying Log Disparate Impact using Kaiser Family Foundation data


```{r }
# Based on code here: https://rstudio.github.io/leaflet/choropleths.html
# Using data here: https://www.kff.org/health-costs/issue-brief/state-data-and-policy-actions-to-address-coronavirus/#stateleveldata

# Set up the US map
#install.packages("geojsonio")
library(htmltools)
library(geojsonio)
library(tidyverse)
library(leaflet)

# Initiaties the geo dataframe
states.import <- geojsonio::geojson_read("json/us-states.json", what = "sp")

```

Data Initialization & Imports...

```{r}

#Re-initialize states
states <- states.import 

# Initialize map 
m <- leaflet(states) %>%
  setView(-96, 37.8, 4) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))

m2 <- m
m3 <- m

# Import provider capacity
provider_capacity <- read_csv("provider_capacity.csv")

# Import state testing 
state_covid_testing <- read_csv("state_covid_testing.csv")

# Import state testing 
state_covid_testing <- read_csv("state_covid_testing.csv")

# Import at risk adults
at_risk_adults <- read_csv("at_risk_adults.csv")

```

Structuring the Data:

```{r}

## Provider Capacity (Hospital beds) fixing
# Fix column names
colnames(provider_capacity) <- c("NAME","total_hosp_beds","hosp_beds_per_1000","total_CHCs","CHC_delivery_sites")
provider_capacity$p_hosp_beds <-provider_capacity$hosp_beds_per_1000/1000 

# Calculate pUS
pUS <- as.numeric(provider_capacity[which(provider_capacity$NAME=="United States"),"p_hosp_beds"])

# ldi.fct <- function(x) {log((x/(1-x))/(pUS/(1-pUS)))} # In case we need a stand-alone definition...

hosp_beds_ldi <- unlist(lapply(provider_capacity$p_hosp_beds, FUN=function(x){log((x/(1-x))/(pUS/(1-pUS)))}))

provider_capacity <- data.frame(provider_capacity, hosp_beds_ldi)

provider_capacity <- provider_capacity[match(states$NAME, provider_capacity$NAME),]

provider_capacity <- provider_capacity[1:52,]

states <- data.frame(states, "hosp_beds_ldi"=provider_capacity$hosp_beds_ldi) # Append to states

## COVID-19 Testing fixing
colnames(state_covid_testing) <- c("NAME","total_num_tests","tests_pos_results")
# Inner join to add population
state_covid_testing <- left_join(state_covid_testing, population, by = c('NAME'))

state_covid_testing <- state_covid_testing %>% 
  mutate(tests_per_1000 = total_num_tests / Population)

pUS.2 <- as.numeric(state_covid_testing[which(state_covid_testing$NAME=="United States"),"tests_per_1000"])

tests_ldi <- unlist(lapply(state_covid_testing$tests_per_1000, FUN=function(x){log((x/(1-x))/(pUS.2/(1-pUS.2)))}))

state_covid_testing <- data.frame(state_covid_testing, tests_ldi)

state_covid_testing <- state_covid_testing[match(states$NAME, state_covid_testing$NAME),]

state_covid_testing <- state_covid_testing[1:52,]

states <- data.frame(states, "tests_ldi"=state_covid_testing$tests_ldi) # Append to states

## At-risk Adults fixing
# Fix column names 
# Columns okay for at risk

# Calculate pUS
pUS.3 <- as.numeric(at_risk_adults[which(at_risk_adults$NAME=="United States"),"p_at_risk_adults"])

at_risk_ldi <- unlist(lapply(at_risk_adults$p_at_risk_adults, FUN=function(x){log((x/(1-x))/(pUS.3/(1-pUS.3)))}))

at_risk_adults <- data.frame(at_risk_adults, at_risk_ldi)

at_risk_adults <- at_risk_adults[match(states$NAME, at_risk_adults$NAME),]

at_risk_adults <- at_risk_adults[1:52,]

states <- data.frame(states, "at_risk_ldi"=at_risk_adults$at_risk_ldi) # Append to states

```

Plot: Disparity Index, Total Hospital Beds/State

```{r}
bins <- c(-1, -.75, -.5, -.25, 0, .25, .5, .75, 1)
pal <- colorBin("YlOrRd", domain = states$hosp_beds_ldi, bins = bins, reverse=TRUE)

labels <- sprintf(
  "<strong>%s</strong><br/>
  At Risk Adults DI: %g<br/>
  Total Tests DI: %g<br/>
  <span style='background-color: #e1eaea'>Hospital Beds DI: %g</span>",
  states$NAME, states$at_risk_ldi, states$tests_ldi, states$hosp_beds_ldi
) %>% lapply(htmltools::HTML)

m <- m %>% addPolygons(
  fillColor = ~pal(hosp_beds_ldi),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")) %>% 
  
  addLegend(pal = pal, values = ~hosp_beds_ldi, opacity = 0.7, title = "Disparity Index<br/>Hospital Beds",
  position = "bottomright")

m

```

Plot: Disparity Index, Total COVID-19 Testing/State

```{r}
bins2 <- c(-3, -2, -1, -.5, 0, .5, 1, 2, 3)
pal2 <- colorBin("YlOrRd", domain = states$tests_ldi, bins = bins2, reverse=FALSE)

labels2 <- sprintf(
  "<strong>%s</strong><br/>
  At Risk Adults DI: %g<br/>
  <span style='background-color: #e1eaea'>Total Tests DI: %g</span><br/>
  Hospital Beds DI: %g",
  states$NAME, states$at_risk_ldi, states$tests_ldi, states$hosp_beds_ldi
) %>% lapply(htmltools::HTML)

m2 <- m2 %>% addPolygons(
  fillColor = ~pal2(tests_ldi),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = labels2,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")) %>% 
  
  addLegend(pal = pal2, values = ~tests_ldi, opacity = 0.7, title = "Disparity Index<br/>Total Tests",
  position = "bottomright")

m2

```

Plot: Disparity Index, Total At-Risk Adults/State

```{r}
bins3 <- c(-0.5, -0.3, -.1, 0, 0.1, 0.3, 0.5)
pal3 <- colorBin("YlOrRd", domain = states$at_risk_ldi, bins = bins3, reverse=TRUE)

labels3 <- sprintf(
  "<strong>%s</strong><br/>
  <span style='background-color: #e1eaea'>At Risk Adults DI: %g</span><br/>
  Total Tests DI: %g<br/>
  Hospital Beds DI: %g",
  states$NAME, states$at_risk_ldi, states$tests_ldi, states$hosp_beds_ldi
) %>% lapply(htmltools::HTML)

m3 <- m3 %>% addPolygons(
  fillColor = ~pal3(at_risk_ldi),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = labels3,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")) %>% 
  
  addLegend(pal = pal3, values = ~at_risk_ldi, opacity = 0.7, title = "Disparity Index<br/>At Risk Adults",
  position = "bottomright")

m3

```

```{r}

```

