---
title: "R Notebook"
output: html_notebook
---
```{r}
# Install and load relevant packages
# install.packages("tidyverse")
library(tidyverse)
# install.packages("ggplot2")
library(ggplot2)
# install.packages("sf")
library(sf)
# install.packages("dplyr")
library(dplyr)
```

```{r}
# load aggregated social determinants attributes data
ag_Det <- read_csv('aggregated_determinants.csv')
#View(ag_Det)

# view rank of destructive determinants from most apparent to least
des_rank <- ag_Det[c("chr_code","des_count")]

des_rank <- des_rank[order(-des_rank$des_count),]
#View(des_rank)

pro_rank <- ag_Det[c("chr_code", "pro_count")]

pro_rank <- pro_rank[order(-pro_rank$pro_count),]
#View(pro_rank)

# printing the top pro/des features

des_feat_temp <- c('Social Associations','African American','Air Quality','Hispanic','Socio-Economic') # top 5 des features for USA

pro_feat_temp <- c('Rural', 'Non-Hispanic White', 'Excessive Drinking', '20th Percentile Income', 'Older Than 65')

des_feat <- (filter(ag_Det, chr_code %in% des_feat_temp))
View(des_feat)

pro_feat <- (filter(ag_Det, chr_code %in% pro_feat_temp))
View(pro_feat)
```



