---
title: "DARL Project Status Notebook Template"
author: "Student Name"
date: "16 September 2020"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
subtitle: "DARL Project Name"
---

## Instructions: Submitting Notebook via github (DELETE BEFORE SUBMISSION)

* Use this notebook is a template for your weekly project status assignment. 
* Use the sections starting with **Weekly Work Summary** as your outline for your submitted notebook.
* Summarize ALL of your work in this notebook; **if you don't show and/or link to your work here, it doesn't exist for us!**

1. Create a fresh github branch of your team's project repository in which to do your work. Use a branch name line `darl-yourname-date`

1. Create a **copy** of this notebook file in the `DARL-2020-Notebooks` sub-directory of your team's github repository using the following naming convention

   * `darl_rcsid_ddmmmyyyy.Rmd` (your notebook source file) 
   * `darl_rcsid_ddmmmyyyy.html` (your knitted notebook)
   * For example, `darl_erickj4_16Sep2020.Rmd` and `darl_erickj4_16Sep2020.html`
   * **Please** don't make up your own naming syntax!

2. Document **all** the work you did on your assigned project this week **using the outline below.** 

3. You MUST include figures and/or tables to illustrate your work. *Screen shots are okay*, but include something!

4. You MUST include links to other important resources (knitted HTMl files, Shiny apps). See the guide below for help.

5. You MUST commit the source (`.Rmd`) and knitted (`.html`) versions of your notebook and push to github

6. **Submit a pull request** on github.rpi.edu. Please notify Dr. Erickson if you don't see your notebook merged within one day. 

7. **DO NOT MERGE YOUR PULL REQUESTS YOURSELF!!**

See the Grading Rubric for guidance on how the contents of this notebook will be graded: https://bit.ly/32OeY44

## Guide to linking to your knitted notebook on github (DELETE BEFORE SUBMISSION)

Part of the assignment is to provide a link to your knitted notebook on github. This section explains how to link to knitted notebooks (ie HTML) files.

1. For files merged with the master on the public github, provide a direct link in your notebook using the following example pattern:

    * Preface: `https://htmlpreview.github.io/? `
    * Repo and branch: `https://raw.githubusercontent.com/TheRensselaerIDEA/COVID-Twitter/master/ `
    * Directory and file: `DARL-2020-Notebooks/status_notebook_template.html'

* Example for projects on the public github (COVIDMINDER, COVID Twitter):

https://htmlpreview.github.io/?https://raw.githubusercontent.com/TheRensselaerIDEA/COVID-Twitter/master/HACL-2020-Notebooks/status_notebook_template.html 

2. For files merged with the master on the RPI github (e.g. Back-to-School, StudySafe, SafeCampus) you need a different syntax; here's a few examples:

    * https://pages.github.rpi.edu/DataINCITE/DARL-2020/Notebooks/status_notebook_template.html
    * https://pages.github.rpi.edu/DataINCITE/DARL-2020/Circadian/status_notebook_template.html
    * https://pages.github.rpi.edu/DataINCITE/IDEA-COVID-WarRoom/DARL-2020-Notebooks/status_notebook_template.html
    
To obtain this link, browse to your merged html on http://github.rpi.edu , grab the link from the address bar of your browser, and insert `pages` into the subdomain of the address as shown above. 

3. Test your link by pasting in a browser and verifying that you see your notebook
4. Paste your working link into the assignment form on LMS. 

You may also want to use this technique to reference other notebooks on github. 

## Guide to linking to Shiny Apps (DELETE BEFORE SUBMISSION)

In your notebook you can also link to Shiny apps you and others have created

* On the cluster, create a sub-directory called `ShinyApps` in your home directory

    * In RStudio in the **Terminal** tab, `cd ~`
    * Then `mkdir ShinyApps`
    * You only need to do this once
    
* In your new `ShinyApps` sub-directory, create a sub-directory to contain your app

    * In the **Terminal** tab, `cd ~/ShinyApps` 
    * Then `mkdir yourcoolapp` (if `yourcoolapp` is the name of your app)
    * Then copy all of the files associated with your app (esp. the `app.R`) in that directory
    
* Alternatively, you can create a symbolic link in that directory, "pointing" to your working directory. In this way your shared app will always be up-to-date.

    * In the **Terminal** tab, `cd ~/ShinyApps` 
    * Then (for example) `ln -s /home/yourrcs/yourappdirectory yourcoolapp` 

* You can now share your app on the RPI network using this syntax:

    * `http://lp01.idea.rpi.edu/shiny/yourrcs/yourcoolapp/` 

## REQUIRED: Weekly Work Summary	

**NOTE:** Follow an outline format; use bullets to express individual points. 

* RCS ID: **Always** include this!
* Project Name: **Always** include this!
* Branch Name: **Always** include this!
* Summary of work since last week 

    * Describe the important aspects of what you worked on and accomplished
    
* Summary of github commits 

    * include branch name(s)
    * include browsable links to all external files on github
    * Include links to shared Shiny apps
    
* List of presentations,  papers, or other outputs

    * Include browsable links (see Instructions)
    
* List of references (if necessary) 
* Indicate any use of group shared code base
* Indicate which parts of your described work were done by you or as part of joint efforts

## Personal Contribution	

* Clearly defined, unique contribution(s) done by you: code, ideas, writing...

## Discussion of Primary Findings 	

* Discuss primary findings: 

    * What did you want to know? 
    * How did you go about finding it? 
    * What did you find?
	
* **Required:** Provide illustrating figures and/or tables

    * Screen shots are acceptable 
    * If your figures are "live," either include source code embedded in notebook or provide github location for their source scripts

