---
title: "ProtoNotebook"
output: html_document
---

```{r setup, include=FALSE}

setwd("/data/Social_Determinants")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../")

```

```{r echo = F, results = 'hide',  warning=FALSE, message=FALSE}

#### Library and Data Imports ####
## Load essential R packages
source("Modules/Source.R")
## Load in model outputs per state:
source("Modules/load_model_output.R")

```

```{r echo = F, results = 'hide',  warning=FALSE, message=FALSE}
### P_value Table explanation
per_state_p_vals <- "<h4><b>Color-coordinate P-Value Summaries per parameter in the model per state?</b></h4>
Here, <span style='color:#c35442'><b>red</b></span> indicates non-significance (p > 0.10)<br><br> 
<span style='color:#d58570'><b>light red</b></span> indicates significance (0.05 < p < 0.10)<br><br> 
<span style='color:#d4e6e8'><b>light blue</b></span> indicates significance (0.01 < p < 0.05)<br><br> 
<span style='color:#94c0c6'><b>blue</b></span> indicates significance (p < 0.01)<br><br>"

p_vals_heatmap <- "<h4><b>P-Value heat map per parameter per state, p-values adjusted via Benjamin Hochberg procedure</b></h4>
<h4><b> to reduce likelihood of false positives in detecting significant parameters.</b></h4>
<h3>Here, <span style='color:#c35442'><b>red</b></span> indicates significant values (p < 0.05)<br><br> 
and <span style='color:#000000'><b>black</b></span> indicates lack of data or a data corruption<br><br>"

p_vals_heatmap2 <- "<h4><b>What values are significant in increasing MR? Decreasing?</b></h4>
<h2> The values represented here are equivalent to those in the previous heatmap. The purpose of this heatmap
is to highlight which parameters are significant in either increasing or decreasing MR. Like the previously
reported p-values, these were adjusted using the Benjamin Hochberg procedure.</h2>
Here, <span style='color:#c35442'><b>red</b></span> indicates values significant (p < 0.05) at increasing MR<br><br> 
<span style='color:#0016FF'><b>blue</b></span> indicates values significant (p < 0.05) at decreasing MR<br><br> 
<span style='color:#CACAD3'><b>grey</b></span> indicates values that are not significant (p > 0.05) at increasing or decreasing MR<br><br> 
and <span style='color:#000000'><b>black</b></span> indicates lack of data or a data corruption<br><br>"
```

  `r per_state_p_vals`

```{r echo = F}


  color_format <- function(x, na.rm = TRUE) {
  
  ifelse(x >0.10,
         
         cell_spec(x, "html", background = "#c35442", color = "#000000"),  # RED (over .1)
         ifelse(x>0.05,
                cell_spec(x, "html", background ="#d58570", color = "#000000"),  # (over .05)
                ifelse(x>0.01,
                       cell_spec(x, "html", background ="#d4e6e8", color = "#000000"), # (over .01)
                       cell_spec(x, "html", background ="#94c0c6", color = "#000000")))) # (under .01)
  
  }
  rounder <- function(x, na.rm = TRUE) {
    round(x, digits = 3)
  }
  
  t2 <- as_tibble(states.all_p)
  library(kableExtra)
  
  t2 %>%
  mutate_if(is.double, rounder, na.rm = TRUE) %>%
  mutate_if(is.double, color_format, na.rm = TRUE) %>%
  kable(format = "html", escape = F, row.names = TRUE) %>%
  kable_styling(full_width = F) 
  
```


`r p_vals_heatmap`

```{r echo = F}
  
# p_value heatmap 

  t2 <- as_tibble(as.data.frame(apply(states.adjusted_p, 2, as.numeric)))
  t3 <- as_tibble(states.adjusted_p)
  
  
  t2 <- dplyr::select(t2, -c("coefficients"))
  t2 <- as.matrix(t2)
  for ( i in 1:dim(t2)[1]){
    for ( k in 1:dim(t2)[2]) {
      if  ( !is.na(t2[i,k]) &&  t2[i,k] < 0.05 ) {
        t2[i,k] = 0.0   # if the value is significant, floor it to 0 to "highlight" it as red on the heatmap
      } 
    }
  }
  
  coefs <- t3$coefficients
  coefs <- str_replace_all(coefs, '\\(', '')
  coefs <- str_replace_all(coefs, '\\)', ' ')
  coefs <- str_replace(coefs, "scale", '')
  coefs <- str_replace(coefs, "factor", '')
  coefs <- str_replace(coefs, "log", '')
  
  t2 <- t(t2)
  
  
  png(filename="Notebooks/pheat1.png",height=10,width=7,res=200,units="in")
  gplots::heatmap.2(t2, 
                    main = "Pvals StateSummary Heatmap", 
                    ylab = "State", 
                    xlab = "factor", 
                    trace = 'none', 
                    na.color = "black", 
                    dendrogram = "row", 
                    labRow = colnames(t2), 
                    labCol = coefs, 
                    margins = c(8,3), 
                    lwid = c(0.25,0.75), 
                    #lhei = c(0.2,0.8), 
                    cexRow = 0.7, 
                    cexCol = 1, 
                    srtCol = 45, 
                    offsetCol = 0.1, 
                    offsetRow = 0.1)
  
```


`r p_vals_heatmap2`

```{r echo = F}
  

  set_na_2_1 <- function(x, na.rm = FALSE) {
    x = 1.000
  }  

  state_c <- as_tibble(as.data.frame(apply(states.adjusted_c, 2, as.numeric)))
  state_c <- dplyr::select(state_c, -c("coefficients"))
  state_c <- as.matrix(state_c)
  state_p <- as_tibble(as.data.frame(apply(states.adjusted_p, 2, as.numeric)))
  state_p <- dplyr::select(state_p, -c("coefficients"))
  state_p <- as.matrix(state_p)
  t3 <- as_tibble(states.adjusted_p)
  state_heat <- matrix(nrow = dim(state_p)[1] , ncol = dim(state_p)[2])
  

  
  for ( i in 1:dim(state_p)[1]){
    for ( k in 1:dim(state_p)[2]) {
      if (is.na(state_p[i,k])){
        state_heat[i,k] = NA
      } else if (state_p[i,k] < 0.05) {
        if (state_c[i,k] < 1.0) {
          state_heat[i,k] = 0.0
        } else if (state_c[i,k] > 1.0){
          state_heat[i,k] = 1
        } else {
          state_heat[i,k] = 0.5
        }
      } else { # grey val, heat = 0.5
        state_heat[i,k] = 0.5
     }
    }
  }
 
  
  color_palette <- colorRampPalette(c("blue", "grey", "red"))(n = 3)
  
  coefs <- t3$coefficients
  coefs <- str_replace_all(coefs, '\\(', '')
  coefs <- str_replace_all(coefs, '\\)', ' ')
  coefs <- str_replace(coefs, "scale", '')
  coefs <- str_replace(coefs, "factor", '')
  coefs <- str_replace(coefs, "log", '')

  
  state_heat <- t(state_heat)
  length(coefs)
  state$state_heat <- as.data.frame(state_heat, row.names = colnames(state_p) )
  colnames(state$state_heat) <- coefs
  #view(state$state_heat)
  
  
  png(filename="Notebooks/pheat2.png",height=10,width=7,res=200,units="in")
  heatmap.2(state_heat, 
            col = color_palette, 
            main = "Effect on MRR per variable per state", 
            ylab = "State", 
            xlab = "factor", 
            trace = 'none', 
            na.color = "black", 
            labRow = colnames(state_p), 
            labCol = coefs, 
            offsetRow = 1, 
            margins = c(10,4), 
            srtCol = 45, 
            dendrogram = "row", 
            Colv = FALSE)


```


```{r echo = F}
  
# Normalize MRRs to MR by subtracting 1 and dividing by stdev for each state... output as table

  state_c <- as.data.frame(states.all_c)
  coefs <- state_c$coefficients
  
  coefs_clean <- c("hispanic", "pct_blk", "pct_asian", "pct_white", "pct_native", "pct_age65", "medhouseholdincome", "pct_obesity", "pct_diabetes", "LungCancer", "COPD", "AdultAsthma", "PediatricAsthma", "All.Cause.death_rate", "state")
  states <- c("AL", "AR", "AZ", "CA", "CT","CO", "DE", "FL", "GA", "IA", "ID", "IL", "IN", "KS", "KY",
            "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NM", "NJ", "NV", 
            "NY", "OH", "OK", "OR", "PA", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY")
  
  # Split the data on state
  statesplit <- split(model_input, model_input$state)

  # Ignore states with less than 2 counties
  for (name in names(statesplit)) {
    if (nrow(statesplit[[name]]) < 2){
      statesplit <- statesplit[names(statesplit) != name]
    }
  }
  
  state_MRs <- array(dim = c(length(states),length(coefs)))
  
  
  for (i in 1:length(names(statesplit))) {
    name = names(statesplit)[i]
    # Ignore states having issues
    if (name %in% c("AZ", "CT", "DE", "RI"))
      next
    state_data <- statesplit[[name]]
      
    state_data <- subset(state_data, select = c(fips, Deaths, hispanic, pct_blk, pct_asian, pct_white, pct_native, medhouseholdincome, pct_obesity, pct_age65, pct_diabetes, LungCancer, AdultChronicLungDisease, COPD, AdultAsthma, PediatricAsthma,  Despair.death_rate, All.Cause.death_rate, Cardiovascular.death_rate, population))
    
    b <- paste(name, ".summary", sep= "")
    model_output <- eval(as.name(b))
    this_state_Cs <- model_output$coefficients[,1]
    names <- names(this_state_Cs)
    this_state_Cs <- unname(this_state_Cs)
    
    if (!(name %in% states)) {
      print(name)
      next
    }
    
    this_state_MRs <- array(dim = c(length(coefs)))
    
    for ( j in 1:length(names)) {
      coef = names[j] 
      sdev <- case_when (
        coef == "scale(hispanic)"                ~ sd(state_data$hispanic, na.rm = TRUE) ,
        coef == "scale(pct_blk)"                 ~ sd(state_data$pct_blk, na.rm = TRUE) ,
        coef == "scale(pct_asian)"               ~ sd(state_data$pct_asian, na.rm = TRUE) ,
        coef == "scale(pct_white)"               ~ sd(state_data$pct_white, na.rm = TRUE) ,
        coef == "scale(pct_native)"              ~ sd(state_data$pct_native, na.rm = TRUE) ,
        coef == "scale(pct_age65)"               ~ sd(state_data$pct_age65, na.rm = TRUE) ,
        coef == "scale(log(medhouseholdincome))" ~ sd(state_data$medhouseholdincome, na.rm = TRUE) ,
        coef == "scale(pct_obesity)"             ~ sd(state_data$pct_obesity, na.rm = TRUE) ,
        coef == "scale(pct_diabetes)"            ~ sd(state_data$pct_diabetes, na.rm = TRUE) ,
        coef == "scale(LungCancer)"              ~ sd(state_data$LungCancer, na.rm = TRUE) ,
        coef == "scale(COPD)"                    ~ sd(state_data$COPD, na.rm = TRUE) ,
        coef == "scale(AdultAsthma)"             ~ sd(state_data$AdultAsthma, na.rm = TRUE) ,
        coef == "scale(PediatricAsthma)"         ~ sd(state_data$PediatricAsthma, na.rm = TRUE) ,
        coef == "scale(All.Cause.death_rate)"    ~ sd(state_data$All.Cause.death_rate, na.rm = TRUE),
        TRUE                                     ~ -100
      )
      if (!is.na(sdev) && sdev != -100) {
        this_state_MRs[which(coefs %in% c(coef))] = (this_state_Cs[j]-1.0)/sdev
      }
    }
    if (length(state_MRs[which(states %in% c(name)),]) != length(this_state_MRs)) {
      #print(length(state_MRs[which(states %in% c(name)),]))
      #print(length(this_state_MRs))
      stop()
    } else {
      state_MRs[which(states %in% c(name)),] = this_state_MRs
    }
  }
  
  
  t0 <- as.data.frame(state_MRs)
  t1 <- as_tibble(t0)
  
  colnames(t1) <- as.character(coefs)
  t2 <- t1 %>% 
    mutate(state = states)
  
  saveRDS(t2, "states_normalize.rds")


```

```{r echo = F}
  
    nat <- national
    coefs <- row.names(nat$coefficients)
  
    mo_in <-subset(model_input, select = c(fips, Deaths, hispanic, pct_blk, pct_asian, pct_white, pct_native, medhouseholdincome, pct_obesity, pct_age65, pct_diabetes, LungCancer, AdultChronicLungDisease, COPD, AdultAsthma, PediatricAsthma,  Despair.death_rate, All.Cause.death_rate, Cardiovascular.death_rate, population)) 
  
    nat_Cs <- nat$coefficients[,1]
    names <- names(nat_Cs)
    
    nat_MRs <- array(dim = c(length(coefs)))
    
    for ( j in 1:length(names)) {
      coef = names[j] 
      sdev <- case_when (
        coef == "scale(hispanic)"                ~ sd(mo_in$hispanic, na.rm = TRUE) ,
        coef == "scale(pct_blk)"                 ~ sd(mo_in$pct_blk, na.rm = TRUE) ,
        coef == "scale(pct_asian)"               ~ sd(mo_in$pct_asian, na.rm = TRUE) ,
        coef == "scale(pct_white)"               ~ sd(mo_in$pct_white, na.rm = TRUE) ,
        coef == "scale(pct_native)"              ~ sd(mo_in$pct_native, na.rm = TRUE) ,
        coef == "scale(pct_age65)"               ~ sd(mo_in$pct_age65, na.rm = TRUE) ,
        coef == "scale(log(medhouseholdincome))" ~ sd(mo_in$medhouseholdincome, na.rm = TRUE) ,
        coef == "scale(pct_obesity)"             ~ sd(mo_in$pct_obesity, na.rm = TRUE) ,
        coef == "scale(pct_diabetes)"            ~ sd(mo_in$pct_diabetes, na.rm = TRUE) ,
        coef == "scale(LungCancer)"              ~ sd(mo_in$LungCancer, na.rm = TRUE) ,
        coef == "scale(COPD)"                    ~ sd(mo_in$COPD, na.rm = TRUE) ,
        coef == "scale(AdultAsthma)"             ~ sd(mo_in$AdultAsthma, na.rm = TRUE) ,
        coef == "scale(PediatricAsthma)"         ~ sd(mo_in$PediatricAsthma, na.rm = TRUE) ,
        coef == "scale(All.Cause.death_rate)"    ~ sd(mo_in$All.Cause.death_rate, na.rm = TRUE),
        TRUE                                     ~ -100
      )
      if (!is.na(sdev) && sdev != -100) {
        nat_MRs[which(coefs %in% c(coef))] = (nat_Cs[j]-1.0)/sdev
      }
    }

    t1 <- as_tibble(nat_MRs)
    
    t2 <- t1 %>%
      mutate(coefficients = names)
    saveRDS(t2, "national_normalize.rds")

```


```{r echo = F}

  # make GWAS per state per 305 vars
  # rerun state models with new variables

    library("leaflet")
    # vars to pick from 
 #   var_i = "Intercept"  "hispanic"  "pct_blk"  "pct_asian"  "pct_white"  "pct_native"  "q_popdensity 2" "q_popdensity 3" "q_popdensity 4" "q_popdensity 5" "medhouseholdincome"   "pct_obesity"  "pct_age65"  "pct_diabetes"  "LungCancer"  "COPD"  "AdultAsthma"  "PediatricAsthma"  "All.Cause.death_rate" 
    var_i = as.name("pct_blk") 
    #state$state_heat$pct_blk
    #colors <- c("grey","#426C85","#67a9cf","#d1e5f0","#f7f7f7","#fddbc7","#ef8a62","#b2182b")
    colors <- c("blue", "grey", "red")
    #bins <- c(5, 2, 1, .2, -.2, -1, -2, -5,-Inf)
    bins <- c(-0.25, 0.25, 0.75, 1.25)
    pal2 <- leaflet::colorBin(colors, domain = state$state_heat$pct_blk, bins = bins, reverse=FALSE)
    labels2 <- sprintf(
      "<strong>%s</strong><br/>
      Mortality Rate P-val: %.2g",
      colnames(state_p), state$state_heat$pct_blk
    ) %>% lapply(htmltools::HTML)
    
    leaflet(states.shapes) %>%
      setView(-96, 37.8, 4) %>% 
      addPolygons(
        fillColor = ~pal2(state$state_heat$pct_blk),
        weight = 2,
        opacity = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.7,
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE),
        label = labels2,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",
          direction = "auto")) %>% 
      addLegend(pal = pal2, 
                values = ~state$state_heat$pct_blk, 
                opacity = 0.7, 
                title = paste("Mortality Rate  Ratio per " , var_i, sep = ""),
                position = "bottomright"
                ) %>%
      addProviderTiles("MapBox", options = providerTileOptions(
        id = "mapbox.light",
        accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))
```


```{r echo = F}

  # use GWAS_ADJ_P and GWAS_MRR to say for which states there are significant protective and destructive variables

  s = ""
  for (state in colnames(GWAS_MRR)) {
    s <- paste(s, state, ": ", sep = "")
    
    prt <- c(NA)
    des <- c(NA)
    for (itr in 1:length(GWAS_ADJ_P[[state]])) {
      if (is.na(GWAS_ADJ_P[[state]][itr]) == FALSE  && GWAS_ADJ_P[[state]][itr] < 0.05 ) {
        if (is.na(GWAS_MRR[[state]][itr]) == FALSE  &&  GWAS_MRR[[state]][itr]  >= 1.0 ) {
          #des <- c(des, GWAS_MRR[[state]][itr])
          des <- c(des, itr)
        } else {
          #prt <- c(prt, GWAS_MRR[[state]][itr])
          prt <- c(prt, itr)
        }
      }
    }
  
    if (length(prt) > 1) {
      s <- paste(s, "protective variables include: ", sep = "")
      for ( i  in 2:length(prt) ) {
        if (i != length(prt)) {
          s <- paste(s, colnames(model_input)[prt[i]], ", ", sep = "")
        } else {
          s <- paste(s, colnames(model_input)[prt[i]], " ", sep = "")
        }
      }
    } else {
      s <- paste(s, "no protective variables; ", sep = "")
    }
    
    if (length(des) > 1) {
      s <- paste(s, "destructive variables include: ", sep = "")
      for ( i  in 2:length(des) ) {
        if (i != length(des)) {
          s <- paste(s, colnames(model_input)[des[i]], ", ", sep = "")
        } else {
          s <- paste(s, colnames(model_input)[des[i]], "", sep = "")
        }
      }
    } else {
      s <- paste(s, "no destructive variables;", sep = "")
    }
    
    s <- paste(s, "\n", sep ="")
  }

  cat(s)


```
  
  
```{r echo = F}
  # Libraries
  library(ggplot2)
# Create data

for (state in colnames(GWAS_MRR)) {
  
  state = "WA"
  state
   s <- paste("GENERATING FIGURE FOR ", state, sep = "")
   print(s)
  
   prt <- c(NA)
    des <- c(NA)
    for (itr in 1:length(GWAS_ADJ_P[[state]])) {
      if (is.na(GWAS_ADJ_P[[state]][itr]) == FALSE  && GWAS_ADJ_P[[state]][itr] < 0.05 ) {
        if (is.na(GWAS_MRR[[state]][itr]) == FALSE  &&  GWAS_MRR[[state]][itr]  >= 1.0 ) {
          des <- c(des, itr)
        } else {
          prt <- c(prt, itr)
        }
      }
    }
    #prt[2:length(prt)]
    vals  <- c(NA)
    names <- c(NA)
    if (length(prt) > 1){
      names <- colnames(model_input)[prt[2:length(prt)]]
      vals <- GWAS_MRR[[state]][prt[2:length(prt)]]
    }
    if (length(des) > 1){
      names <- c(names, colnames(model_input)[des[2:length(des)]])
      vals <- c(vals, GWAS_MRR[[state]][des[2:length(des)]])
    }
    
    if (length(names) == 1) {
      print("Insufficient data or no protective or destructive variables in this state.")
      next
    }

    
    data <- data.frame(
      y=names[2:length(names)], 
      x=vals[2:length(names)]
    )
    
    #view(data)
    title <- paste(state, " Protective and Destructive Variables", sep = "")
    data <- data %>% 
      mutate(`Effect on MRR` = ifelse(x<1,"Protective", "Destructive"))
     
    data$y <- factor(data$y, levels = data$y)

    # Plot
    h <- (length(vals)-1) * 0.4
    f <- paste("Notebooks/state_GWAS_results/", state, "SDWAS.png", sep = "")
    png(filename=f,height=h,width=7,res=200,units="in")
    ggplot(data, aes(x=x, y=y)) +
      geom_point() +
  #    geom_rect(data=NULL,aes(ymin=0,ymax=length(prt)-1.5,xmin=-Inf,xmax=Inf),
   #                 fill="#94c0c6")+
 #    geom_rect(data=NULL,aes(ymin=length(prt)-1.5,ymax=Inf,xmin=-Inf,xmax=Inf),
   #                 fill="#c35442")+
      geom_segment( aes(x=x, xend=1, y=y, yend=y, color = `Effect on MRR`), size=1.3, alpha=0.9 ) +
    #  scale_color_manual(values = c("#9ea2a2", "#9ea2a2")) +
      #geom_segment(aes(x = Inf, xend = Inf, y = Inf, yend = Inf, color = `Effect on MRR`), size = 1, alpha = 0.9) +
      scale_color_manual(values = c("#c35442", "#2b517f")) +
      geom_point() +
      ylab("Interested Variable") +
      xlab("MRR of Interested Variable") +
      ggtitle(title) +
      geom_segment( aes(x=1, xend=1, y=0, yend = length(vals)), size = 1.0)
    dev.off()
}
```