---
title: "COVID vs Despair"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)

cdc.data

despair.data<- subset(cdc.data, death_cause == "Despair")

#covid_data_states<- read.csv("covid_data_states.csv")

covid_TS_counties_long.cases

keeps.despair <- c("county_name","county_fips","death_rate")
despair.data.updated = despair.data[keeps.despair]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updated = covid_TS_counties_long.cases[keeps.covid]

COVIDdespair.all = merge(despair.data.updated, covid.data.updated, by.x="county_fips", by.y="countyFIPS")

COVIDdespair<- distinct(COVIDdespair.all)

ggplot(data=COVIDdespair, aes(x=death_rate,y=p_deaths)) +
  geom_point()

cor.test(COVIDdespair$death_rate,COVIDdespair$p_deaths)

ggplot(data=COVIDdespair, aes(x=death_rate, y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE)


```

```{r}
library(gridExtra)
#>50
cdc.data
#despair.data<- subset(cdc.data, death_cause == "Despair", period == "2015-2017")
despair.data <- cdc.data[ which(cdc.data$death_cause=='Despair'
& cdc.data$period== '2015-2017'), ]

covid_TS_counties_long.cases
#coviddeathallcounties1<- subset(covid_TS_counties_long.cases, date == "2020-03-15")
#coviddeathallcounties <- subset(coviddeathallcounties1, deaths >= 5, select=c("County","countyFIPS","deaths", "p_deaths"))
coviddeathallcounties <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths >= 50 ),]
#& covid_TS_counties_long.cases$date=="2020-03-15"), ]
#coviddeathallcounties[coviddeathallcounties$date >= "2020-04-01" & coviddeathallcounties$date <= "2020-04-03",]

keeps.despair <- c("county_name","county_fips","death_rate")
despair.data.updated = despair.data[keeps.despair]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updated = coviddeathallcounties[keeps.covid]

COVIDdespair.all = merge(despair.data.updated, covid.data.updated, by.x="county_fips", by.y="countyFIPS")


#COVIDdespair<- distinct(COVIDdespair.all)
COVIDdespair<- distinct(COVIDdespair.all,county_fips, .keep_all= TRUE)

#COVIDdespair <- unique(COVIDdespair[ , 1:3 ] )

#ggplot(data=COVIDdespair, aes(x=death_rate,y=p_deaths)) +
#  geom_point()

cor.test(COVIDdespair$death_rate,COVIDdespair$p_deaths)
#-0.05098315 

ggplot(data=COVIDdespair, aes(x=death_rate, y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Deaths of Despair Rate vs COVID Mortality Rate (>50)") +
  xlab("Death of Despair Rate") +
  ylab("COVID Mortality Rate")



#0-50
cdc.data
despair.data <- cdc.data[ which(cdc.data$death_cause=='Despair'
& cdc.data$period== '2015-2017'), ]

covid_TS_counties_long.cases
coviddeathallcountiesunder50 <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths <=50 ),]

keeps.despairunder50 <- c("county_name","county_fips","death_rate")
despair.data.updated.under50 = despair.data[keeps.despairunder50]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updated = coviddeathallcountiesunder50[keeps.covid]

COVIDdespair.all.under50 = merge(despair.data.updated.under50, covid.data.updated, by.x="county_fips", by.y="countyFIPS")

COVIDdespairunder50<- distinct(COVIDdespair.all.under50,county_fips, .keep_all= TRUE)

cor.test(COVIDdespairunder50$death_rate,COVIDdespairunder50$p_deaths)
#-0.07721489 
p1<-ggplot(data=COVIDdespairunder50, aes(x=death_rate, y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Deaths of Despair Rate vs COVID Mortality Rate (0-50)") +
  xlab("Death of Despair Rate") +
  ylab("COVID Mortality Rate")

log10.covid.0_50<-(log10(COVIDdespairunder50$p_deaths))
log10.despair.0_50<- (log10(COVIDdespairunder50$death_rate))
COVIDdespairunder50$log10covid= log10.covid.0_50
COVIDdespairunder50$log10despair=log10.despair.0_50
p1_5<-ggplot(data=COVIDdespairunder50, aes(x=log10despair, y=log10covid)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Deaths of Despair Rate vs COVID Mortality Rate (0-50)") +
  xlab("Death of Despair Rate") +
  ylab("COVID Mortality Rate")

#50-100
cdc.data
despair.data <- cdc.data[ which(cdc.data$death_cause=='Despair'
& cdc.data$period== '2015-2017'), ]

covid_TS_counties_long.cases
coviddeathallcounties50100 <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths >=50|covid_TS_counties_long.cases$deaths <=100 ),]

keeps.despair50100 <- c("county_name","county_fips","death_rate")
despair.data.updated.50100 = despair.data[keeps.despair50100]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updated50100 = coviddeathallcounties50100[keeps.covid]

COVIDdespair.all.50100 = merge(despair.data.updated.50100, covid.data.updated50100, by.x="county_fips", by.y="countyFIPS")

COVIDdespair50100<- distinct(COVIDdespair.all.50100,county_fips, .keep_all= TRUE)

cor.test(COVIDdespair50100$death_rate,COVIDdespair50100$p_deaths)
#-0.02593088 
p2<-ggplot(data=COVIDdespair50100, aes(x=death_rate, y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Deaths of Despair Rate vs COVID Mortality Rate (50-100)") +
  xlab("Death of Despair Rate") +
  ylab("COVID Mortality Rate")

log10.covid.50_100<-(log10(COVIDdespair50100$p_deaths))
log10.despair.50_100<- (log10(COVIDdespair50100$death_rate))
COVIDdespair50100$log10covid= log10.covid.50_100
COVIDdespair50100$log10despair=log10.despair.50_100
p2_5<-ggplot(data=COVIDdespair50100, aes(x=log10despair, y=log10covid)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Deaths of Despair Rate vs COVID Mortality Rate (50-100)") +
  xlab("Death of Despair Rate") +
  ylab("COVID Mortality Rate")

#>100
cdc.data
despair.data <- cdc.data[ which(cdc.data$death_cause=='Despair'
& cdc.data$period== '2015-2017'), ]

covid_TS_counties_long.cases
coviddeathallcountiesgreater100 <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths >=100 ),]

keeps.despairgreater100 <- c("county_name","county_fips","death_rate")
despair.data.updated.greater100 = despair.data[keeps.despairgreater100]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updatedgreater100 = coviddeathallcountiesgreater100[keeps.covid]

COVIDdespair.all.greater100 = merge(despair.data.updated.greater100, covid.data.updatedgreater100, by.x="county_fips", by.y="countyFIPS")

COVIDdespairgreater100<- distinct(COVIDdespair.all.greater100,county_fips, .keep_all= TRUE)

cor.test(COVIDdespairgreater100$death_rate,COVIDdespairgreater100$p_deaths)

#-0.07142184
p3<-ggplot(data=COVIDdespairgreater100, aes(x=death_rate, y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Deaths of Despair Rate vs COVID Mortality Rate (>100)") +
  xlab("Death of Despair Rate") +
  ylab("COVID Mortality Rate")

log10.covid.greater100<-(log10(COVIDdespairgreater100$p_deaths))
log10.despair.greater100<- (log10(COVIDdespairgreater100$death_rate))
COVIDdespairgreater100$log10covid= log10.covid.greater100
COVIDdespairgreater100$log10despair=log10.despair.greater100
p3_5<-ggplot(data=COVIDdespairgreater100, aes(x=log10despair, y=log10covid)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Deaths of Despair Rate vs COVID Mortality Rate (>100)") +
  xlab("Death of Despair Rate") +
  ylab("COVID Mortality Rate")

grid.arrange(p1, p2, p3, nrow = 3)
grid.arrange(p1_5,p2_5,p3_5, nrow =3)
p1
p2
p3
p1_5
p2_5
p3_5
```
```{r}
cor.test(COVIDdespairunder50$log10covid,COVIDdespairunder50$log10despair)
cor.test(COVIDdespair50100$log10covid,COVIDdespair50100$log10despair)
cor.test(COVIDdespairgreater100$log10covid,COVIDdespairgreater100$log10despair)

```


suicide
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)

aaa<-read.csv("2020CHR.csv")

data.suicide <- aaa %>% dplyr::select(FIPS, State, County, Suicide.Rate..Age.Adjusted.)

covid_TS_counties_long.cases<- read.csv("covid_TS_counties_long.cases.csv")

coviddeathallcounties <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths >= 50 ),]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updated = coviddeathallcounties[keeps.covid]

COVIDsuicide.all = merge(data.suicide, covid.data.updated, by.x="FIPS", by.y="countyFIPS")

COVIDsuicide<- distinct(COVIDsuicide.all,FIPS, .keep_all= TRUE)

cor.test(COVIDsuicide$Suicide.Rate..Age.Adjusted.,COVIDsuicide$p_deaths)
#-0.139

ggplot(data=COVIDsuicide, aes(x=Suicide.Rate..Age.Adjusted., y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Suicide Rate (Age Adjusted) vs COVID Mortality Rate (>50)") +
  xlab("Suicide Rate (Age Adjusted)") +
  ylab("COVID Mortality Rate")


#50
aaa<-read.csv("2020CHR.csv")

data.suicide <- aaa %>% dplyr::select(FIPS, State, County, Suicide.Rate..Age.Adjusted.)

covid_TS_counties_long.cases<- read.csv("covid_TS_counties_long.cases.csv")

coviddeathallcountiesunder50 <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths <= 50 ),]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updatedunder50 = coviddeathallcountiesunder50[keeps.covid]

COVIDsuicide.all.under50 = merge(data.suicide, covid.data.updatedunder50, by.x="FIPS", by.y="countyFIPS")

COVIDsuicide.under50<- distinct(COVIDsuicide.all.under50,FIPS, .keep_all= TRUE)

cor.test(COVIDsuicide.under50$Suicide.Rate..Age.Adjusted.,COVIDsuicide.under50$p_deaths)
#-0.139

g1<-ggplot(data=COVIDsuicide.under50, aes(x=Suicide.Rate..Age.Adjusted., y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Suicide Rate (Age Adjusted) vs COVID Mortality Rate (0-50)") +
  xlab("Suicide Rate (Age Adjusted)") +
  ylab("COVID Mortality Rate")

log10.covid.under50<-(log10(COVIDsuicide.under50$p_deaths))
COVIDsuicide.under50$log10covid= log10.covid.under50
g1_5<-ggplot(data=COVIDsuicide.under50, aes(x=Suicide.Rate..Age.Adjusted., y=log10covid)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Suicide Rate (Age Adjusted) vs COVID Mortality Rate (0-50)") +
  xlab("Suicide Rate (Age Adjusted)") +
  ylab("COVID Mortality Rate")

#50-100
aaa<-read.csv("2020CHR.csv")

data.suicide <- aaa %>% dplyr::select(FIPS, State, County, Suicide.Rate..Age.Adjusted.)

covid_TS_counties_long.cases<- read.csv("covid_TS_counties_long.cases.csv")

coviddeathallcounties50_100 <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths >= 50|covid_TS_counties_long.cases$deaths <= 100 ),]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updated50_100 = coviddeathallcounties50_100[keeps.covid]

COVIDsuicide.all.50_100 = merge(data.suicide, covid.data.updated50_100, by.x="FIPS", by.y="countyFIPS")

COVIDsuicide.50_100<- distinct(COVIDsuicide.all.50_100,FIPS, .keep_all= TRUE)

cor.test(COVIDsuicide.50_100$Suicide.Rate..Age.Adjusted.,COVIDsuicide.50_100$p_deaths)
#-0.139

g2<-ggplot(data=COVIDsuicide.50_100, aes(x=Suicide.Rate..Age.Adjusted., y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Suicide Rate (Age Adjusted) vs COVID Mortality Rate (50-100)") +
  xlab("Suicide Rate (Age Adjusted)") +
  ylab("COVID Mortality Rate")

log10.covid.50_100<-(log10(COVIDsuicide.50_100$p_deaths))
COVIDsuicide.50_100$log10covid= log10.covid.50_100
g2_5<-ggplot(data=COVIDsuicide.50_100, aes(x=Suicide.Rate..Age.Adjusted., y=log10covid)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Suicide Rate (Age Adjusted) vs COVID Mortality Rate (50-100)") +
  xlab("Suicide Rate (Age Adjusted)") +
  ylab("COVID Mortality Rate")

#>100
aaa<-read.csv("2020CHR.csv")

data.suicide <- aaa %>% dplyr::select(FIPS, State, County, Suicide.Rate..Age.Adjusted.)

covid_TS_counties_long.cases<- read.csv("covid_TS_counties_long.cases.csv")

coviddeathallcountiesgreater100 <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths >= 100 ),]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updatedgreater100 = coviddeathallcountiesgreater100[keeps.covid]

COVIDsuicide.all.greater100 = merge(data.suicide, covid.data.updatedgreater100, by.x="FIPS", by.y="countyFIPS")

COVIDsuicide.greater100<- distinct(COVIDsuicide.all.greater100,FIPS, .keep_all= TRUE)

cor.test(COVIDsuicide.greater100$Suicide.Rate..Age.Adjusted.,COVIDsuicide.greater100$p_deaths)
#-0.139

g3<-ggplot(data=COVIDsuicide.greater100, aes(x=Suicide.Rate..Age.Adjusted., y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Suicide Rate (Age Adjusted) vs COVID Mortality Rate (>100)") +
  xlab("Suicide Rate (Age Adjusted)") +
  ylab("COVID Mortality Rate")

log10.covid.greater100<-(log10(COVIDsuicide.greater100$p_deaths))
COVIDsuicide.greater100$log10covid= log10.covid.greater100
g3_5<-ggplot(data=COVIDsuicide.greater100, aes(x=Suicide.Rate..Age.Adjusted., y=log10covid)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("Suicide Rate (Age Adjusted) vs COVID Mortality Rate (>100)") +
  xlab("Suicide Rate (Age Adjusted)") +
  ylab("COVID Mortality Rate")

g1
g2
g3
g1_5
g2_5
g3_5
grid.arrange(g1, g2, g3, nrow = 3)
grid.arrange(g1_5,g2_5,g3_5, nrow=3)

```
```{r}
cor.test(COVIDsuicide.under50$Suicide.Rate..Age.Adjusted.,COVIDsuicide.under50$log10covid)
cor.test(COVIDsuicide.50_100$Suicide.Rate..Age.Adjusted.,COVIDsuicide.50_100$log10covid)
cor.test(COVIDsuicide.greater100$Suicide.Rate..Age.Adjusted.,COVIDsuicide.greater100$log10covid)
```



excessive drinking
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)

#0-50
aaa<-read.csv("2020CHR.csv")

data.excessdrink <- aaa %>% dplyr::select(FIPS, State, County,X..Excessive.Drinking)

covid_TS_counties_long.cases<- read.csv("covid_TS_counties_long.cases.csv")

coviddeathallcounties <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths <= 50 ),]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updated = coviddeathallcounties[keeps.covid]

COVIDexcessdrink.all = merge(data.excessdrink, covid.data.updated, by.x="FIPS", by.y="countyFIPS")

COVIDexcessdrink<- distinct(COVIDexcessdrink.all,FIPS, .keep_all= TRUE)

cor.test(COVIDexcessdrink$X..Excessive.Drinking,COVIDexcessdrink$p_deaths)

gg1<-ggplot(data=COVIDexcessdrink, aes(x=X..Excessive.Drinking, y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("% Excessive Drinking vs COVID Mortality Rate (<50)") +
  xlab("% Excessive Drinking") +
  ylab("COVID Mortality Rate")

log10.covid.greater100<-(log10(COVIDexcessdrink$p_deaths))
COVIDexcessdrink$log10covid= log10.covid.greater100
gg1_5<-ggplot(data=COVIDexcessdrink, aes(x=X..Excessive.Drinking, y=log10covid)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("% Excessive Drinking vs COVID Mortality Rate (<50)") +
  xlab("% Excessive Drinking") +
  ylab("COVID Mortality Rate")

#50-100
aaa<-read.csv("2020CHR.csv")

data.excessdrink <- aaa %>% dplyr::select(FIPS, State, County, X..Excessive.Drinking)

covid_TS_counties_long.cases<- read.csv("covid_TS_counties_long.cases.csv")

coviddeathallcounties50_100 <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths >= 50|covid_TS_counties_long.cases$deaths <= 100 ),]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updated50_100 = coviddeathallcounties50_100[keeps.covid]

COVIDexcessdrink.all.50_100 = merge(data.excessdrink, covid.data.updated50_100, by.x="FIPS", by.y="countyFIPS")

COVIDexcessdrink.50_100<- distinct(COVIDexcessdrink.all.50_100,FIPS, .keep_all= TRUE)

cor.test(COVIDexcessdrink.50_100$X..Excessive.Drinking,COVIDexcessdrink.50_100$p_deaths)

gg2<-ggplot(data=COVIDexcessdrink.50_100, aes(x=X..Excessive.Drinking, y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("% Excessive Drinking vs COVID Mortality Rate (50-100)") +
  xlab("% Excessive Drinking") +
  ylab("COVID Mortality Rate")

log10.covid.50_100<-(log10(COVIDexcessdrink.50_100$p_deaths))
COVIDexcessdrink.50_100$log10covid= log10.covid.50_100
gg2_5<-ggplot(data=COVIDexcessdrink.50_100, aes(x=X..Excessive.Drinking, y=log10covid)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("% Excessive Drinking vs COVID Mortality Rate (50-100)") +
  xlab("% Excessive Drinking") +
  ylab("COVID Mortality Rate")

#>100
aaa<-read.csv("2020CHR.csv")

data.excessdrink <- aaa %>% dplyr::select(FIPS, State, County, X..Excessive.Drinking)

covid_TS_counties_long.cases<- read.csv("covid_TS_counties_long.cases.csv")

coviddeathallcountiesgreater100 <- covid_TS_counties_long.cases[ which(covid_TS_counties_long.cases$deaths >= 100 ),]

keeps.covid <- c("County","countyFIPS","p_deaths")
covid.data.updatedgreater100 = coviddeathallcountiesgreater100[keeps.covid]

COVIDexcessdrink.all.greater100 = merge(data.excessdrink, covid.data.updatedgreater100, by.x="FIPS", by.y="countyFIPS")

COVIDexcessdrink.greater100<- distinct(COVIDexcessdrink.all.greater100,FIPS, .keep_all= TRUE)

cor.test(COVIDexcessdrink.greater100$X..Excessive.Drinking,COVIDexcessdrink.greater100$p_deaths)

gg3<-ggplot(data=COVIDexcessdrink.greater100, aes(x=X..Excessive.Drinking, y=p_deaths)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("% Excessive Drinking vs COVID Mortality Rate (>100)") +
  xlab("% Excessive Drinking") +
  ylab("COVID Mortality Rate")

log10.covid.greater100<-(log10(COVIDexcessdrink.greater100$p_deaths))
COVIDexcessdrink.greater100$log10covid= log10.covid.greater100
gg3_5<-ggplot(data=COVIDexcessdrink.greater100, aes(x=X..Excessive.Drinking, y=log10covid)) + 
  geom_point() + geom_smooth(method="lm",se= TRUE) +
  ggtitle("% Excessive Drinking vs COVID Mortality Rate (>100)") +
  xlab("% Excessive Drinking") +
  ylab("COVID Mortality Rate")

gg1
gg2
gg3
gg1_5
gg2_5
gg3_5
grid.arrange(gg1, gg2, gg3, nrow = 3)
grid.arrange(gg1_5,gg2_5,gg3_5, nrow=3)
```
```{r}
cor.test(COVIDexcessdrink$X..Excessive.Drinking,COVIDexcessdrink$log10covid)
cor.test(COVIDexcessdrink.50_100$X..Excessive.Drinking,COVIDexcessdrink.50_100$log10covid)
cor.test(COVIDexcessdrink.greater100$X..Excessive.Drinking,COVIDexcessdrink.greater100$log10covid)
```

